title:             N01ch1v3
email:             it.mahaifeng@gmail.com
description:       生活只有苟且，并没有诗和远方
author:            N01ch1v3
baseurl:           "/"
url:               "http://N01ch1v3.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   N01ch1v3
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
